Bump jsonschema to ^3
Previous requirement on 2.6.0 causes poetry commands to fail
with error:

    [AttributeError]
    module 'jsonschema' has no attribute 'Draft7Validator'